# Generated by Django 3.2.3 on 2021-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInformation',
            fields=[
                ('whiteboard_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('whiteboard_image', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('course_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=256)),
                ('course_name', models.CharField(max_length=256)),
                ('start_data', models.CharField(max_length=256)),
                ('start_time', models.CharField(max_length=256)),
                ('during_time', models.IntegerField()),
                ('detail', models.CharField(max_length=65536, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentInformation',
            fields=[
                ('comment_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256)),
                ('whiteboard_id', models.CharField(max_length=256)),
                ('ques_id', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=256)),
                ('comment_time', models.CharField(max_length=256)),
                ('comment_detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FileInformation',
            fields=[
                ('doc_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=256)),
                ('doc_name', models.CharField(max_length=256)),
                ('doc_data', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInformation',
            fields=[
                ('ques_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=256)),
                ('create_time', models.CharField(max_length=256)),
                ('ppt_page', models.IntegerField()),
                ('ques_detail', models.CharField(max_length=65536)),
                ('ques_status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('user_nickname', models.BooleanField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=256)),
                ('phone_num', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('school', models.CharField(max_length=256, null=True)),
                ('faculty', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('status', models.CharField(default='S', max_length=256)),
            ],
        ),
    ]
